// WARNING: This file has automatically been generated on Wed, 29 Dec 2021 19:01:05 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "faiss.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

