// WARNING: This file has automatically been generated on Mon, 10 Jan 2022 11:46:52 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "faiss.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

