// WARNING: This file has automatically been generated on Wed, 29 Dec 2021 19:01:05 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package gofaiss

/*
#cgo pkg-config: faiss
#include "faiss.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// FAISS_IO_FLAG_MMAP as defined in c_api/index_io_c.h:34
	FAISS_IO_FLAG_MMAP = 1
	// FAISS_IO_FLAG_READ_ONLY as defined in c_api/index_io_c.h:35
	FAISS_IO_FLAG_READ_ONLY = 2
)

// FaissMetricType as declared in c_api/Index_c.h:40
type FaissMetricType int32

// FaissMetricType enumeration from c_api/Index_c.h:40
const (
	METRIC_INNER_PRODUCT FaissMetricType = iota
	METRIC_L2            FaissMetricType = 1
	METRIC_L1            FaissMetricType = 2
	METRIC_Linf          FaissMetricType = 3
	METRIC_Lp            FaissMetricType = 4
	METRIC_Canberra      FaissMetricType = 20
	METRIC_BrayCurtis    FaissMetricType = 21
	METRIC_JensenShannon FaissMetricType = 22
)

// FaissQuantizerType as declared in c_api/IndexScalarQuantizer_c.h:29
type FaissQuantizerType int32

// FaissQuantizerType enumeration from c_api/IndexScalarQuantizer_c.h:29
const (
	QT_8bit         FaissQuantizerType = iota
	QT_4bit         FaissQuantizerType = 1
	QT_8bit_uniform FaissQuantizerType = 2
	QT_4bit_uniform FaissQuantizerType = 3
	QT_fp16         FaissQuantizerType = 4
	QT_8bit_direct  FaissQuantizerType = 5
	QT_6bit         FaissQuantizerType = 6
)

// FaissErrorCode as declared in c_api/error_c.h:29
type FaissErrorCode int32

// FaissErrorCode enumeration from c_api/error_c.h:29
const (
	OK             FaissErrorCode = iota
	UNKNOWN_EXCEPT FaissErrorCode = -1
	FAISS_EXCEPT   FaissErrorCode = -2
	STD_EXCEPT     FaissErrorCode = -4
)
